grafana:
  defaultDashboardsEnabled: true
  sidecar:
    datasources:
      enabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.observability.svc.cluster.local:3100
      isDefault: false

prometheus:
  prometheusSpec:
    retention: 3d
    scrapeInterval: 30s
    evaluationInterval: 30s

alertmanager:
  enabled: true

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false
