apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - servicemonitor.yaml
labels:
  - pairs:
      app.kubernetes.io/name: demo-api
      app.kubernetes.io/part-of: platform-engineering-demo
    includeSelectors: true
